// Project settings. Keep the object below valid JSON: the Python tools read it too.
window.MV_PROJECT = {
  "title": "I'm Upping My P(doom) · 灯",
  "audio": "../../../pdoom-video/audio/pdoom.mp3",
  "data": [
    "../anime-pdoom/data/audio.js",
    "../anime-pdoom/data/lyrics.js"
  ],
  "from": 0.0,
  "to": 156.696,
  "fps": 24,
  "drawRate": 12,
  "width": 1920,
  "height": 1080,
  "kits": [
    "anime",
    "lumen",
    "illust"
  ],
  "scripts": [
    "lib/fonts.js",
    "frames/A6v.js",
    "frames/E5v.js",
    "frames/H1v.js",
    "frames/C7v.js",
    "frames/A5v.js",
    "frames/A2v.js",
    "frames/E2v.js",
    "frames/G1v.js",
    "frames/H3v.js",
    "frames/H4v.js",
    "frames/E7v.js",
    "frames/D1v.js",
    "frames/D4v.js",
    "frames/C11v.js",
    "frames/H2v.js",
    "frames/A7v.js",
    "frames/A4v.js",
    "frames/C1v.js",
    "frames/C9v.js",
    "frames/F2v.js",
    "frames/G2v.js",
    "frames/E1v.js",
    "frames/C6v.js",
    "frames/C5v.js",
    "frames/A3v.js",
    "frames/B5v.js",
    "frames/B1v.js",
    "frames/B4v.js",
    "frames/B3v.js",
    "frames/H4.js",
    "frames/H3.js",
    "frames/H2.js",
    "frames/H1.js",
    "frames/G2.js",
    "frames/G1.js",
    "frames/F4.js",
    "frames/F3.js",
    "frames/F2.js",
    "frames/F1.js",
    "frames/E7.js",
    "frames/E6.js",
    "frames/E5.js",
    "frames/E4.js",
    "frames/E3.js",
    "frames/E2.js",
    "frames/D4.js",
    "frames/D3.js",
    "frames/D2.js",
    "frames/D1.js",
    "frames/C11.js",
    "frames/C10.js",
    "frames/C9.js",
    "frames/C8.js",
    "frames/C7.js",
    "frames/C6.js",
    "frames/C5.js",
    "frames/C4.js",
    "frames/C3.js",
    "frames/C2.js",
    "frames/C2off.js",
    "frames/C1.js",
    "frames/B8.js",
    "frames/B7.js",
    "frames/B6.js",
    "frames/B5.js",
    "frames/B3.js",
    "frames/B2.js",
    "frames/B1.js",
    "frames/A7.js",
    "frames/A6.js",
    "frames/A5.js",
    "frames/A4.js",
    "frames/A3.js",
    "frames/A1.js",
    "frames/E1.js",
    "frames/B4.js",
    "frames/A2.js",
    "lib/art.js",
    "lib/spots.js",
    "lib/akari.js"
  ],
  "scenes": [
    "lab",
    "screen",
    "eye",
    "nervous",
    "loss",
    "drop",
    "spark_out",
    "bow",
    "door",
    "prompt1",
    "hook1",
    "foom",
    "room",
    "shrooms",
    "shoggoth",
    "shinigami",
    "first_thread",
    "bench",
    "singularity",
    "accel",
    "atoms",
    "prompt2",
    "hook2",
    "basilisk",
    "moon",
    "omega",
    "flops",
    "meeting",
    "corridor",
    "obsolete",
    "leftturn",
    "cdr",
    "prompt3",
    "hook3",
    "paperclips",
    "killswitch",
    "nowhere",
    "fuse",
    "blues",
    "tower",
    "disobey",
    "dense",
    "fence",
    "gpu",
    "askew",
    "hook4",
    "loom",
    "masked",
    "recursive",
    "see",
    "show",
    "sunrise",
    "hairclip",
    "monitor"
  ],
  "post": {
    "grain": 0.04,
    "vignette": 0.25
  },
  "background": "#000"
};
