"""Shared helpers for the mv-kit Python tools: read project.js, resolve paths, write data files."""
import json
import re
import subprocess
from pathlib import Path

KIT = Path(__file__).resolve().parent.parent


def project_dir(p):
    d = Path(p).expanduser().resolve()
    if d.is_file():
        d = d.parent
    if not (d / 'project.js').exists():
        cand = KIT / 'projects' / str(p)
        if (cand / 'project.js').exists():
            return cand
        raise SystemExit(f'no project.js in {d}')
    return d


def load_project(p):
    """project.js is `window.MV_PROJECT = { ...JSON... };` — the object must stay valid JSON."""
    d = project_dir(p)
    src = (d / 'project.js').read_text(encoding='utf-8')
    body = src[src.index('{'):src.rindex('}') + 1]
    body = re.sub(r'^\s*//.*$', '', body, flags=re.M)  # allow whole-line // comments
    try:
        cfg = json.loads(body)
    except json.JSONDecodeError as e:
        raise SystemExit(f'{d / "project.js"}: the object after "=" must be plain JSON ({e})')
    cfg['_dir'] = d
    return cfg


def save_project(cfg):
    d = cfg['_dir']
    data = {k: v for k, v in cfg.items() if not k.startswith('_')}
    (d / 'project.js').write_text('// Project settings. Keep the object below valid JSON: the Python tools read it too.\n'
                                  'window.MV_PROJECT = ' + json.dumps(data, indent=2, ensure_ascii=False) + ';\n', encoding='utf-8')


def audio_path(cfg):
    a = cfg.get('audio')
    if not a:
        raise SystemExit('project.js has no "audio"')
    p = (cfg['_dir'] / a).resolve()
    if not p.exists():
        raise SystemExit(f'audio file not found: {p}')
    return p


def stems_dir(cfg):
    d = cfg['_dir'] / 'stems'
    return d if d.exists() else None


def write_data(cfg, name, obj):
    """data/<name>.json (for tools and people) + data/<name>.js (loaded by the page, works from file://)."""
    dd = cfg['_dir'] / 'data'
    dd.mkdir(exist_ok=True)
    js = json.dumps(obj, ensure_ascii=False, separators=(',', ':'))
    (dd / f'{name}.json').write_text(json.dumps(obj, ensure_ascii=False, indent=1) if len(js) < 200_000 else js, encoding='utf-8')
    (dd / f'{name}.js').write_text(f'// generated by mv-kit analysis — edit {name}.json / the fix files and re-run instead\n'
                                   f'window.MV_DATA = window.MV_DATA || {{}};\nMV_DATA.{name} = {js};\n', encoding='utf-8')
    return dd / f'{name}.json'


def decode(path, sr=22050):
    """Decode any audio file to mono float64 with ffmpeg."""
    import numpy as np
    out = subprocess.run(['ffmpeg', '-v', 'error', '-i', str(path), '-f', 'f32le', '-ac', '1', '-ar', str(sr), '-'],
                         capture_output=True, check=True).stdout
    return np.frombuffer(out, np.float32).astype(np.float64)


def duration(path):
    out = subprocess.run(['ffprobe', '-v', 'error', '-show_entries', 'format=duration', '-of', 'csv=p=0', str(path)],
                         capture_output=True, text=True, check=True).stdout
    return float(out.strip())
